# Generated by Django 2.0.5 on 2021-03-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accruals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20)),
                ('date_of_scholarship_accrual', models.DateField()),
                ('amount_of_money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=20)),
                ('faculty_code', models.CharField(max_length=20)),
                ('department_head_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_code', models.CharField(max_length=20)),
                ('faculty_name', models.CharField(max_length=20)),
                ('deanery_employee_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fellows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20)),
                ('scholarship_type_code', models.CharField(max_length=20)),
                ('beginning_of_the_accrual_period', models.DateField()),
                ('ending_of_the_accrual_period', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.IntegerField()),
                ('group_name', models.CharField(max_length=20)),
                ('group_head_student_code', models.CharField(max_length=20)),
                ('issuing_department_code', models.CharField(max_length=20)),
                ('сurator_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship_Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_code', models.CharField(max_length=20)),
                ('scholarship_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сurator_code', models.CharField(max_length=20)),
                ('curator_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('group_code', models.IntegerField()),
                ('education_type_code', models.IntegerField()),
                ('personal_reckoning_number', models.IntegerField()),
                ('bank_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Types_of_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type_code', models.IntegerField()),
                ('education_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Types_of_Scholarships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_type_code', models.CharField(max_length=20)),
                ('scholarship_type_name', models.CharField(max_length=20)),
                ('amount_of_money', models.IntegerField()),
            ],
        ),
    ]
