# Generated by Django 3.2 on 2021-04-14 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210414_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='amount_of_money',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='Сумма начисления'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='date_of_scholarship_accrual',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начисления стипендии'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='student_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student', verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код банка'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=120, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код кафедры'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Заведующий кафедрой'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=120, verbose_name='Наименование кафедры'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.faculty', verbose_name='Код факультета'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='deanery_employee_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Декан факультета'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код факультета'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=120, verbose_name='Наименование факультета'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='beginning_of_the_accrual_period',
            field=models.DateField(blank=True, null=True, verbose_name='Начало периода начисления'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='ending_of_the_accrual_period',
            field=models.DateField(blank=True, null=True, verbose_name='Конец периода начисления'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='scholarship_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.types_of_scholarship', verbose_name='Вид стипендии'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='student_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student', verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_head_student_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Староста группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=120, verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='issuing_department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='Код выпускающей кафедры'),
        ),
        migrations.AlterField(
            model_name='group',
            name='сurator_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Код куратора группы'),
        ),
        migrations.AlterField(
            model_name='scholarship_fund',
            name='faculty_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='main.faculty', verbose_name='Код факультета'),
        ),
        migrations.AlterField(
            model_name='scholarship_fund',
            name='scholarship_amount',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Сумма стипендий'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='curator_name',
            field=models.CharField(max_length=200, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='сurator_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='student',
            name='bank_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.bank', verbose_name='Код банка'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.types_of_education', verbose_name='Код вида обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Код группы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='personal_reckoning_number',
            field=models.IntegerField(verbose_name='Номер лицевого счета'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=200, verbose_name='Имя студента'),
        ),
        migrations.AlterField(
            model_name='types_of_education',
            name='education_type_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код вида обучения'),
        ),
        migrations.AlterField(
            model_name='types_of_education',
            name='education_type_name',
            field=models.CharField(choices=[('Grand', 'Грант'), ('Paid basis', 'Платная основа')], max_length=120, verbose_name='Наименование вида обучения'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='amount_of_money',
            field=models.PositiveIntegerField(verbose_name='Сумма выплачиваемой стипендии (₸)'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='scholarship_type_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код вида стипендии'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='scholarship_type_name',
            field=models.CharField(choices=[('common', 'Обычная'), ('increased', 'Повышенная'), ('nominal', 'Именная'), ('social', 'Социальная')], max_length=25, verbose_name='Наименование вида стипендии'),
        ),
    ]
