# Generated by Django 3.2 on 2021-04-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210415_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='types_of_education',
            name='education_type_name',
            field=models.CharField(choices=[('Grand', 'Грант'), ('Paid basis', 'Платная основа')], default='Paid basis', max_length=120, verbose_name='Наименование вида обучения'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='amount_of_money',
            field=models.PositiveIntegerField(verbose_name='Сумма выплачиваемой стипендии, ₸'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='scholarship_type_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код вида стипендии'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='scholarship_type_name',
            field=models.CharField(choices=[('common', 'Обычная'), ('increased', 'Повышенная'), ('nominal', 'Именная'), ('social', 'Социальная')], default='common', max_length=25, verbose_name='Наименование вида стипендии'),
        ),
    ]
