# Generated by Django 3.2 on 2021-04-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210415_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='amount_of_money',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма начисления'),
        ),
        migrations.AlterField(
            model_name='scholarship_fund',
            name='scholarship_amount',
            field=models.PositiveIntegerField(verbose_name='Сумма стипендий'),
        ),
    ]
