# Generated by Django 3.2 on 2021-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210415_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Код студента'),
        ),
    ]
