# Generated by Django 3.2 on 2021-04-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrual',
            name='student_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_head_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='Заведующий кафедрой'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty', verbose_name='Код факультета'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='deanery_employee_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='Декан факультета'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='scholarship_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.types_of_scholarship', verbose_name='Вид стипендии'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='student_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='group',
            name='issuing_department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='Код выпускающей кафедры'),
        ),
        migrations.AlterField(
            model_name='group',
            name='сurator_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.staff', verbose_name='Код куратора группы'),
        ),
        migrations.AlterField(
            model_name='scholarship_fund',
            name='faculty_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.faculty', verbose_name='Код факультета'),
        ),
        migrations.AlterField(
            model_name='student',
            name='bank_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bank', verbose_name='Код банка'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.types_of_education', verbose_name='Код вида обучения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Группа'),
        ),
    ]
