# Generated by Django 3.2 on 2021-04-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210421_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Заведующий кафедрой'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='deanery_employee_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Декан факультета'),
        ),
        migrations.AlterField(
            model_name='group',
            name='сurator_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.staff', verbose_name='Код куратора группы'),
        ),
        migrations.AlterField(
            model_name='types_of_scholarship',
            name='scholarship_type_name',
            field=models.CharField(choices=[('common', 'Обычная'), ('increased', 'Повышенная'), ('nominal', 'Именная'), ('social', 'Социальная')], default='common', max_length=25, verbose_name='Код вида стипендии'),
        ),
    ]
