# Generated by Django 3.2 on 2021-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_scholarship_fund_scholarship_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_of_education',
            name='education_type_name',
            field=models.CharField(choices=[('Грант', 'Grand'), ('Платная основа', 'Paid basis')], default='Платная основа', max_length=120, verbose_name='Наименование вида обучения'),
        ),
    ]
