# Generated by Django 3.2 on 2021-04-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_fellow_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_head_student_code',
        ),
    ]
