# Generated by Django 3.2 on 2021-04-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_group_group_head_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='student_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Код студента'),
        ),
    ]
